#!/bin/bash

srcdir=$(readlink -m $(dirname $0))
source $srcdir/common

print_help() {
    echo "$0 [os type]"
    echo
    echo "This script copies a newly created base domain image to a backup"
    echo "which can then later be recovered via restore-base-domain"
    echo
    echo "Valid os types are: $IMG_TYPES"
    exit 0
}

[ "-h" == "$1" ] && print_help

TYPE=$1

checktype $TYPE
test -z $VMS_DIR && error "VMS_DIR is not set"

vm=zzz-$TYPE

refresh-storage-pools

$VIRSH shutdown zzz-$TYPE > /dev/null 2>&1
virsh_shutdown_wait zzz-$TYPE

sudo rsync -aP $VMS_DIR/zzz-$TYPE.img $VMS_DIR/zzz-$TYPE.bak
