#!/bin/bash

EPEL7_RELEASE="http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm"

useradd admin -G wheel
echo "password" | passwd admin --stdin

mkdir -p /home/admin/.ssh
cp -v /root/.ssh/authorized_keys /home/admin/.ssh

chown -R admin /home/admin/.ssh
chmod go-rw /home/admin/.ssh
chmod go-rw /root/.ssh

restorecon -rv /home/admin
restorecon -rv /root

echo "admin ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
visudo -c

rpm -ivh http://rhos-release.virt.bos.redhat.com/repos/rhos-release/rhos-release-latest.noarch.rpm
rhos-release 6

rpm -ivh $EPEL7_RELEASE

echo "Done"
