#!/bin/bash

useradd admin -G wheel
echo "password" | passwd admin --stdin

mkdir -p /home/admin/.ssh
cp -v /root/.ssh/authorized_keys /home/admin/.ssh

chown -R admin /home/admin/.ssh
chmod go-rw /home/admin/.ssh
chmod go-rw /root/.ssh

restorecon -rv /home/admin
restorecon -rv /root

echo "admin ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
visudo -c

echo "Done"
