#!/bin/bash

srcdir=$(readlink -m $(dirname $0))
source $srcdir/common

print_help() {
    echo "$0 [os type] [num hosts] [base answer file]"
    echo
    echo "This script takes an answer file template and generates one"
    echo "that can be used with the proper number of hosts (controller and"
    echo "compute nodes)."
    echo
    echo "Valid os types are: $IMG_TYPES"
    exit 0
}

[ "-h" == "$1" ] && print_help

TYPE=$1
NUM=$2
BASE=$3

checktype $TYPE
test -z "$NUM" && error "Please provide a host count"
test -z "$BASE" && error "Please provide a base answer file"

sub=$(getsub $TYPE)

cp -vf $BASE packstack.ans
sed -i s/@MGMT@/192.168.$sub.101/ packstack.ans

computes="192.168.$sub.101"
for i in `seq 2 $NUM`; do
    ip="$(( $i + 100))"
    computes="$computes,192.168.$sub.$ip"
done

sed -i s/@COMP@/$computes/ packstack.ans



