#!/bin/bash

srcdir=$(readlink -m $(dirname $0))
source $srcdir/common

TYPE=$1
NUM=$2
SUB=$3
BASE=$4

test -z "$TYPE" && error "Please provide an image type: $IMG_TYPES"
test -z "$NUM" && error "Please provide a host count"
test -z "$SUB" && error "Please provide a subnet"
test -z "$BASE" && error "Please provide a base answer file"

cp -vf $BASE packstack.ans
sed -i s/@MGMT@/192.168.$sub.101/ packstack.ans

computes="192.168.$sub.101"
for i in `seq 2 $count`; do
    ip="$(( $i + 100))"
    computes="$computes,192.168.$sub.$ip"
done

sed -i s/@COMP@/$computes/ packstack.ans



