#!/bin/bash

source $(dirname $0)/common

netscripts=/etc/sysconfig/network-scripts

iface=$1
ip=$2

cat <<EOF | sudo tee $netscripts/ifcfg-$iface
DEVICE=$iface
BOOTPROTO=static
IPADDR=$ip
NETMASK=255.255.255.0
ONBOOT=yes
EOF
