#!/bin/bash

iface=$1
ip=$2

{
    echo "DEVICE=$iface"
    echo "BOOTPROTO=static"
    echo "IPADDR=$ip"
    echo "NETMASK=255.255.255.0"
    echo "ONBOOT=yes"
} > /etc/sysconfig/network-scripts/ifcfg-$iface
