#!/bin/bash

source $(dirname $0)/common

set -v
keystone user-create --name mydemo --pass password
keystone role-create --name mydemo-role
keystone tenant-create --name mydemo-tenant

keystone user-role-add --user-id mydemo --role-id mydemo-role \
    --tenant-id mydemo-tenant
set +v

waitkey
set -v
keystone user-list
set +v

waitkey
set -v
keystone role-list
set +v

waitkey
set -v
keystone tenant-list
set +v

waitkey
set -v
keystone user-role-list
set +v

waitkey
set -v
keystone endpoint-list
set +v

cat <<EOF > keystonerc_mydemo
export OS_USERNAME=mydemo
export OS_TENANT_NAME=mydemo-tenant
export OS_PASSWORD=password
export OS_AUTH_URL=$OS_AUTH_URL
export PS1='[\u@\h \W(keystone_mydemo)]\$ '
EOF

