#!/bin/bash

source $(dirname $0)/common

inst=$1
fip=$2
test -z "$inst" && error "Please provide an instance id"
test -z "$fip" && error "Please provide an ip"

set -v
neutron floatingip-list
neutron floatingip-create external
nova add-floating-ip $inst $fip
