#!/bin/bash

source $(dirname $0)/common

set -v
keystone user-create --name demo2 --pass password
keystone role-create --name demo2-role
keystone tenant-create --name demo2-tenant

keystone user-role-add --user-id demo2 --role-id demo2-role \
    --tenant-id demo2-tenant
set +v

waitkey
set -v
keystone user-list
set +v

waitkey
set -v
keystone role-list
set +v

waitkey
set -v
keystone tenant-list
set +v

waitkey
set -v
keystone user-role-list
set +v

waitkey
set -v
keystone endpoint-list
set +v

cat <<EOF > keystonerc_demo2
export OS_USERNAME=demo2
export OS_TENANT_NAME=demo2-tenant
export OS_PASSWORD=password
export OS_AUTH_URL=$OS_AUTH_URL
export PS1='[\u@\h \W(keystone_demo2)]\$ '
EOF

