#!/bin/bash

source $(dirname $0)/common

inst=$1
test -z "$inst" && error "Please provide an instance id"

set -v
neutron floatingip-list
nova floating-ip-list
neutron floatingip-create external
fip=$(nova floating-ip-list | grep external | tr -d '|' | tr -s ' ' \
    | awk '{print $1}')
nova add-floating-ip $inst $fip
neutron floatingip-list
nova floating-ip-list
