#!/bin/bash -v

source $(dirname $0)/common

test -z "$1" && error "Please provide an instance id"

cinder create --display-name my-vol 1
id=$(nova volume-list | grep my-vol | awk -F '|' '{print $2}' | xargs)
nova volume-attach $1 $id auto
