#!/bin/bash

set -v
neutron net-create external --provider:network_type local \
    --router:external true

neutron subnet-create external 192.168.100.0/24 --disable-dhcp \
    --allocation-pool start=192.168.100.100,end=192.168.100.150 \
    --gateway=192.168.100.1
































































