#!/bin/bash

source $(dirname $0)/common

test -z "$1" && error "Please provide an instance id"

set -v
neutron floatingip-list
neutron floatingip-create external
nova add-floating-ip $1 192.168.100.101
