#!/bin/bash

IMG=http://cloud.fedoraproject.org/fedora-20.x86_64.qcow2

file=$1
test -n "$file" || file="fedora-20.x86_64.qcow2" 

test -f "$file" || wget $IMG -O $file

glance image-delete my-fedora
glance image-create --name my-fedora --disk-format qcow2 \
    --container-format bare --file $file --is-public True

glance image-list
