#!/bin/bash

os-dl-fedora

set -v
glance image-delete my-fedora
glance image-create --name my-fedora --disk-format qcow2 \
    --container-format bare --file fedora20-guest.img --is-public True

glance image-list
