#!/bin/bash

os-dl-cirros

set -v
glance image-delete my-cirros
glance image-create --name my-cirros --disk-format qcow2 \
    --container-format bare --file cirros-guest.img --is-public True

glance image-list
