#!/bin/bash

srcdir=$(readlink -m $(dirname $0))
source $srcdir/common

SYSPREP_OPTS=$(virt-sysprep --list-operations | grep \* | awk '{print $1}' | grep -v -e ssh-userdir | xargs | tr ' ' ',')
VIRSH="sudo virsh"

TYPE=$1

test -z $VMS_DIR && error "VMS_DIR is not set"
test -z "$TYPE" && error "Please provide an image type: $IMG_TYPES"

vm=zzz-$TYPE

sub=$(getsub $TYPE)
ipaddr=192.168.$sub.100
addhost $vm $ipaddr
mac=$(grep "192.168.@SUB@.100" $srcdir/net-mgmt \
    | sed 's/.*mac="\(.*\)" name=.*/\1/')
[ -n "$mac" ] && macopt=",mac=$mac"

{
    $VIRSH destroy $vm
    $VIRSH undefine $vm
    $VIRSH net-destroy $TYPE-mgmt && $VIRSH net-undefine $TYPE-mgmt
    $VIRSH net-destroy $TYPE-priv && $VIRSH net-undefine $TYPE-priv

    foreach_host $TYPE 10 "sudo virsh destroy"
    foreach_host $TYPE 10 "sudo virsh undefine"
} > /dev/null 2>&1

tmp=$(mktemp)

sed -e "s/@NAME@/$TYPE/g" -e "s/@SUB@/$sub/g" $srcdir/net-mgmt > $tmp
$VIRSH net-define $tmp

sed "s/@NAME@/$TYPE/g" $srcdir/net-priv > $tmp
$VIRSH net-define $tmp

$VIRSH net-start $TYPE-mgmt
$VIRSH net-autostart $TYPE-mgmt
$VIRSH net-start $TYPE-priv
$VIRSH net-autostart $TYPE-priv

rm -f $tmp

if [ "$TYPE" == "rhel-6" ]; then
    IMPORT_IMG=$VMS_DIR/bak/$TYPE-guest.img
    test -f $IMPORT_IMG || error "$IMPORT_IMG not present"

    sudo chown $USER $VMS_DIR/$vm.img 2> /dev/null
    rsync -LavP $IMPORT_IMG $VMS_DIR/$vm.img
else 
    virt-builder --hostname $vm --format qcow2 \
        --root-password password:password --size 15 --update $TYPE
fi

sudo virt-sysprep --enable $SYSPREP_OPTS \
    --root-password password:password \
    --script $srcdir/sysprep-$TYPE \
    --firstboot $srcdir/firstboot-$TYPE \
    -a $VMS_DIR/$vm.img

sudo virt-install -n $vm -r 2048 --vcpus 2 --noautoconsole \
    -w network=$TYPE-mgmt$macopt -w network=$TYPE-priv \
    --os-variant=$(osvariant $TYPE) \
    --import --disk path=$VMS_DIR/$vm.img

ssh-clean $vm

sshwait admin@$vm

$ssh admin@$vm sudo yum install yum deltarpm -y
$ssh admin@$vm sudo yum update -y

if [ $(echo $TYPE | grep -e rhel -e centos) ]; then
    $ssh admin@$vm sudo yum install --enablerepo=epel git-all -y
else
    $ssh admin@$vm sudo yum install git-all -y
fi

$ssh admin@$vm sudo yum install nfs-utils emacs-color-theme fpaste \
    yum-config-manager yum-utils yum-plugin-priorities -y

$ssh admin@$vm git clone https://github.com/pmyers/rdo-demo-helper.git

$ssh admin@$vm sudo yum install $(cat $srcdir/devstack-deps | xargs) -y

$ssh admin@$vm "echo 'export PATH=$PATH:~/rdo-demo-helper' >> .bashrc"
