#!/bin/bash

source $(dirname $0)/common

IMG_TYPE=$1
REL=$2
test -z $VMS_DIR && error "VMS_DIR is not set"
test -z "$IMG_TYPE" && error "Please provide an image type: $IMG_TYPES"
test -z "$REL" && REL=icehouse

sudo virsh start zzz-$IMG_TYPE
pingwait zzz-$IMG_TYPE
sleepwait 5
sshwait admin@zzz-$IMG_TYPE

$ssh zzz-$IMG_TYPE "rdo-release $REL"
$ssh zzz-$IMG_TYPE sudo yum install --enablerepo epel \
    --exclude openstack-nova-volume,openstack-savanna \
    $(cat ~/etc/rdo-deps | xargs) -y
