#!/bin/bash

srcdir=$(readlink -m $(dirname $0))
source $srcdir/common

print_help() {
    echo "$0 [os type] [release]"
    echo
    echo "This script is run after prep-base-image creates a single base"
    echo "image and installs all RDO prerequisites on it so that demo"
    echo "installs do not need to download much over the network."
    echo "You might want to consider running backup-base-domain prior to this"
    echo
    echo "Valid os types are: $IMG_TYPES"
    echo "Valid OpenStack releases are: $RDO_RELEASES"
    exit 0
}

[ "-h" == "$1" ] && print_help

TYPE=$1
REL=$2

checktype $TYPE
test -z "$REL" && REL=juno

vm=admin@zzz-$TYPE

foreach_host $TYPE 10 "$VIRSH destroy" > /dev/null 2>&1
foreach_host $TYPE 10 "$VIRSH undefine" > /dev/null 2>&1

$VIRSH start zzz-$TYPE
sshwait $vm

$ssh $vm "cd rdo-demo-helper && git pull && root-ssh-setup"
$ssh $vm "sudo yum install -y $RDO_URL/openstack-$REL/rdo-release-$REL.rpm"
$ssh $vm "sudo yum update -y"
$ssh $vm "sudo yum install openstack-packstack -y"

$ssh $vm "sudo yum-config-manager --enable epel > /dev/null"

$ssh $vm "sudo yum install $(cat $srcdir/rdo-deps | xargs) -y"

pushd $VMS_DIR/bak
$srcdir/os-dl-cirros
$srcdir/os-dl-fedora

rsync -aLP fedora20-guest.img $vm:.
rsync -aLP cirros-guest.img $vm:.
popd

