#!/bin/bash

source $(dirname $0)/common

if [ x"$1" == "x" ]; then
    error "Please specify a release (grizzly, havana)"
fi

sudo yum install -y http://rdo.fedorapeople.org/openstack/openstack-$1/rdo-release-$1.rpm || exit 1

sudo yum update -y

sudo yum install openstack-packstack -y
