#!/bin/bash

srcdir=$(readlink -m $(dirname $0))
source $srcdir/common

TYPE=$1
NUM=$2
REL=$3

test -z "$TYPE" && error "Please provide an image type: $IMG_TYPES"
test -z "$NUM" && NUM=1
test -z "$REL" && REL=icehouse

mgmt=admin@${TYPE}1

sub=$(getsub $TYPE)
FIP=192.168.$sub.200

foreach_hostssh $TYPE $NUM "cd rdo-demo-helper && git pull -nq"

waitkey "Setting up Keystone Users"
$ssh $mgmt ". keystonerc_admin && os-create-tenant"

waitkey "Importing Fedora Guest Image"
$ssh $mgmt ". keystonerc_admin && os-import-fedora"
waitkey "Importing Cirros Guest Image"
$ssh $mgmt ". keystonerc_admin && os-import-cirros"

waitkey "Setting up External Bridge"
$ssh $mgmt "os-setup-brex"
waitkey "Setting up External Bridge in Neutron"
$ssh $mgmt ". keystonerc_admin && os-config-neutron-gre $sub"
waitkey "Setting up Tenant Network"
$ssh $mgmt ". keystonerc_demo && os-config-neutron-gre-tenant"
waitkey "Open Security Groups"
$ssh $mgmt ". keystonerc_demo && os-sec-open"

waitkey "Importing SSH Key"
$ssh $mgmt ". keystonerc_demo && os-import-key"

waitkey "Booting Instance"
$ssh $mgmt ". keystonerc_demo && os-boot-cirros"

waitkey "Associating Floating IP"
$ssh $mgmt ". keystonerc_demo && os-create-floating-ip my-cirros-inst $FIP"

waitkey "Waiting for Instance"
sshwait cirros@$FIP

waitkey "Set up Cinder Volume"
$ssh $mgmt ". keystonerc_demo && os-create-cinder my-cirros-inst"

waitkey "Mount Cinder Volume in Guest"
$ssh cirros@$FIP "sudo /usr/sbin/mkfs.ext4 /dev/vdb"
$ssh cirros@$FIP "sudo mkdir -p /mnt/volume"
$ssh cirros@$FIP "sudo mount /dev/vdb /mnt/volume"
$ssh cirros@$FIP "df -h"
$ssh cirros@$FIP "sudo touch /mnt/volume/test.txt"
$ssh cirros@$FIP "sudo unmount /mnt/volume"

waitkey "Swift Demo"
$ssh $mgmt ". keystonerc_admin && os-demo-swift"
