#!/bin/bash

srcdir=$(readlink -m $(dirname $0))
source $srcdir/common

TYPE=$1
REL=$2

checktype $TYPE
test -z "$REL" && REL=icehouse

vm=admin@zzz-$TYPE

foreach_host $TYPE 10 "$VIRSH destroy" > /dev/null 2>&1
foreach_host $TYPE 10 "$VIRSH undefine" > /dev/null 2>&1

$VIRSH start zzz-$TYPE
sshwait $vm

$ssh $vm "cd rdo-demo-helper && git pull && root-ssh-setup"

$ssh $vm "rdo-release $REL"

$ssh $vm "sudo yum-config-manager --enable epel"

$ssh $vm "sudo yum install $(cat $srcdir/rdo-deps | xargs) -y"

pushd $VMS_DIR/bak
$srcdir/os-dl-cirros
$srcdir/os-dl-fedora

rsync -aLP fedora20-guest.img $vm:.
rsync -aLP cirros-guest.img $vm:.
popd

