#!/bin/bash

dest=./rdo-repos

sync-repo() {
    reposync --setopt=reposdir=$(dirname $0)/rdo.repo \
        -n -p $dest -r $1-openstack-$2
    pushd $dest/$1-openstack-$2
    createrepo .
    popd
}

mkdir -p $dest

sync-repo el6 havana
sync-repo el6 icehouse
sync-repo fedora havana
sync-repo fedora icehouse

