#!/bin/bash

srcdir=$(readlink -m $(dirname $0))
source $srcdir/common

print_help() {
    echo "$0 [os type] [num hosts] [release]"
    echo
    echo "This script is run following rdo|rhos-*-prep and actually runs"
    echo "a demo script to show the OpenStack functionality via the various"
    echo "REST APIs and command line tools"
    echo
    echo "Valid os types are: $IMG_TYPES" 
    echo "Valid OpenStack releases are: $RDO_RELEASES"
    exit 0
}

TYPE=$1
NUM=$2
REL=$3

checktype $TYPE
test -z "$NUM" && NUM=1
test -z "$REL" && REL=juno

mgmt=admin@${TYPE}1

sub=$(getsub $TYPE)

foreach_host $TYPE $NUM "$VIRSH start"
sshwait_hosts $TYPE $NUM

foreach_hostssh $TYPE $NUM "cd rdo-demo-helper && git pull -nq"

# Note: demo tenant is autocreated by Packstack, so os-create-tenant
# simply creates a separate tenant
waitkey "Setting up Keystone Users"
$ssh $mgmt ". keystonerc_admin && os-create-tenant"

waitkey "Importing Fedora Guest Image"
$ssh $mgmt ". keystonerc_admin && os-import-fedora"
waitkey "Importing Cirros Guest Image"
$ssh $mgmt ". keystonerc_admin && os-import-cirros"

# Note: demo tenant has precreated fake network, so disabling manual creation
#
#waitkey "Setting up External Bridge"
#$ssh $mgmt "os-setup-brex"
#waitkey "Setting up External Bridge in Neutron"
#$ssh $mgmt ". keystonerc_admin && os-config-neutron-gre $sub"
#waitkey "Setting up Tenant Network"
#$ssh $mgmt ". keystonerc_demo && os-config-neutron-gre-tenant"

waitkey "Open Security Groups"
$ssh $mgmt ". keystonerc_demo && os-sec-open"

waitkey "Importing SSH Key"
$ssh $mgmt ". keystonerc_demo && os-import-key"

waitkey "Booting Instance"
$ssh $mgmt ". keystonerc_demo && os-boot-cirros"

waitkey "Associating Floating IP"
$ssh $mgmt ". keystonerc_demo && os-create-floating-ip my-cirros-inst"

waitkey "Retieving Floating IP"
fip=$(ssh $mgmt cat my-cirros-inst.fip)

waitkey "Waiting for Instance at $fip"
sshwait cirros@$fip

waitkey "Set up Cinder Volume"
$ssh $mgmt ". keystonerc_demo && os-create-cinder my-cirros-inst"

waitkey "Mount Cinder Volume in Guest"
$ssh cirros@$fip "sudo /usr/sbin/mkfs.ext4 /dev/vdb"
$ssh cirros@$fip "sudo mkdir -p /mnt/volume"
$ssh cirros@$fip "sudo mount /dev/vdb /mnt/volume"
$ssh cirros@$fip "df -h"
$ssh cirros@$fip "sudo touch /mnt/volume/test.txt"

waitkey "Swift Demo"
$ssh $mgmt ". keystonerc_admin && os-demo-swift"
