#!/bin/bash

srcdir=$(readlink -m $(dirname $0))
source $srcdir/common

print_help() {
    echo "$0 [os type] [num hosts]"
    echo
    echo "This script takes a base image, creates a number of guests with"
    echo "that base image as the root, and then boots them as a virtual"
    echo "datacenter on a private network."
    echo
    echo "Valid os types are: $IMG_TYPES"
    exit 0
}

TYPE=$1
NUM=$2

checktype $TYPE
test -z "$NUM" && NUM=1

$srcdir/gen-image $TYPE $NUM || error

foreach_host $TYPE $NUM "$VIRSH start"
sshwait_hosts $TYPE $NUM

foreach_hostssh $TYPE $NUM "cd rdo-demo-helper && git pull && root-ssh-setup"
foreach_hostssh $TYPE $NUM "sudo yum update -y"
