#!/bin/bash

srcdir=$(readlink -m $(dirname $0))
source $srcdir/common

print_help() {
    echo "$0 [os type] [num hosts]"
    echo
    echo "This script restores a set of guests that were saved following"
    echo "a run of rdo-demo-prep, but before actually running the demo"
    echo
    echo "Valid os types are: $IMG_TYPES"
    exit 0
}

[ "-h" == "$1" ] && print_help

TYPE=$1
NUM=$2

checktype $TYPE
test -z "$NUM" && NUM=1
test -z $VMS_DIR && error "VMS_DIR is not set"

foreach_host $TYPE $NUM "$VIRSH destroy" > /dev/null 2>&1
foreach_host $TYPE $NUM virsh_shutdown_wait

for i in `seq 1 $NUM`; do
    image="${TYPE}$i.img"
    rsync -aP $VMS_DIR/$image.bak $VMS_DIR/$image
done

