#!/bin/bash

source $(dirname $0)/common

sudo virsh destroy r6m
sudo virsh destroy r6c1

rsync -avP ~/vms/after-rdo-el6-multi-prep/r6m.img ~/vms/r6m.img
rsync -avP ~/vms/after-rdo-el6-multi-prep/r6c1.img ~/vms/r6c1.img

sudo virsh start r6m
sudo virsh start r6c1

sshwait r6m
sshwait r6c1

$ssh r6m "cd rdo-demo-helper && git pull 2> /dev/null"
$ssh r6c1 "cd rdo-demo-helper && git pull 2> /dev/null"
