#!/bin/bash

dest=./rdo-repos

sync-repo() {
    reposync -c yum.conf -n -p $dest -r $1-openstack-$2
    pushd $dest/$1-openstack-$2
    createrepo .
    popd
}

mkdir -p $dest

sync-repo el7 juno
sync-repo fedora juno

