#!/bin/bash

srcdir=$(readlink -m $(dirname $0))
source $srcdir/common

TYPE=$1
NUM=$2

checktype $TYPE
test -z "$NUM" && NUM=1
test -z $VMS_DIR && error "VMS_DIR is not set"

foreach_host $TYPE $NUM "$VIRSH destroy" > /dev/null 2>&1
foreach_host $TYPE $NUM virsh_shutdown_wait

for i in `seq 1 $NUM`; do
    image="${TYPE}$i.img"
    rsync -aP $VMS_DIR/$image.bak $VMS_DIR/$image
done

