#!/bin/bash

source $(dirname $0)/common

if [ x"$1" == "x" ]; then
    error "Please specify a release (4, 5)"
fi

sudo rhos-release $1

sudo yum update --disablerepo=epel -y

sudo yum install --disablerepo=epel openstack-packstack -y
